# -*- coding: utf-8 -*-
"""Matrizes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBJfsnX1RjpAryNxLdQuKybXb_VGlXmT
"""

from sympy import symbols, Matrix, Rational, diag

A = Matrix([[1,2], [3,0],[-1,4]])
A

B = Matrix(2,3,[1,2,-1,3,0,4])
#{2,3} indica a quantia de linhas e colunas !
B

#Matriz Linha
C = Matrix([[1,2,3]])
C

#Matriz Coluna
D = Matrix([1,2,3])
D

#Matriz quadrada de ordem 3 !
E = Matrix(3,3,(1,2,3,4,5,6,7,8,9))
E

#Diagonalização de Matrizes
diag(1,2,3)

#Elemento especifico
E[2,2]

#Transforma a matriz em uma lista
a = list(A)
a

#Ordem(tamanho) da Matriz
B.shape

E.shape

"""Operações"""

x = symbols("x")
y = symbols("y")
z = symbols("z")

"""Construa uma matrix 2 x 3"""

F = Matrix([[x,y,z], [x+1,y+1,z+1]])
F

G = Matrix([x,y,z])
G

H = Matrix([[1,2,3],[4,5,6]])
H

#Soma de matrizes de mesma ordem, respectiva a soma de cada uma delas
H + F

#H + G ->Ordens diferentes(tamanho) { não funciona }

# Soma {H + F = F + H} comutativa
F+H

#Subtração {H - F != F-H}
H - F

from sympy import zeros, ones, eye

zeros(2) #Matris Nula

ones(10) #Todas as entradas são 1

eye(4) #matriz identidade ->matriz quadrada apenas

