# -*- coding: utf-8 -*-
"""02/05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQ-wgmVJ6Kt-8DRiEP5qXRrkkcY-fsDx
"""

a=7.56454554544554
b=2.10

print(a*b)

print(a+b)



print(a**-1)

print(6**-1)

print(a**2 * a**3)

print(a**5)

print(a**(2+3))

from math import pow

print(pow(a,2))

print(pow(4,1/2))

from fractions import Fraction

print(Fraction(1,2))

arredA = round(a);
print(arredA)

arredA2 = round(a,2)
#qtd de casas apos a virgula
print(arredA2)

c=Fraction(2,3)
print(c)
d = Fraction(1,4)
print(d)

pow(a,c)

somaE = c+d
print("A soma de c e d é", somaE)

from numpy import polyadd, polysub, polymul, polydiv

Coef1= [3,2,-1]
#3x^2 + 2x + -1

Coef2 = [4,-1,2]

add = polyadd(Coef1, Coef2)
print(add)

mul = polymul(Coef1, Coef2)
print(mul)

div = polydiv(Coef1, Coef2)
print(div)

from sympy.abc import x
from sympy import factor

from sympy.functions.combinatorial.factorials import factorial2
fac = factor(x**2+-16*x)
print(fac)
fac2 = factor(x**2+-16)
print(fac2)

fac3 = factor(x**2 - 4*x + 4)
print(fac3)
#(x + a)^2 = x^2 - 2ax + a^2

fac4 = factor(x**2 + x -6)
print(fac4)

